CREATE TABLE IF NOT EXISTS  `cw_external_customer` (
    `id` int(11) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT UNIQUE,
    `login_id` bigint(20) NOT NULL DEFAULT '1',
    `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `active` tinyint(1) NOT NULL DEFAULT '0',
    `user_code`  VARCHAR(32) NOT NULL DEFAULT 'AAA1786',
    `fname`  VARCHAR(256)  ,
    `lname`  VARCHAR(256)  ,
    `phone` VARCHAR(256) NOT NULL DEFAULT '02031290000',
    `phone_type` varchar(32) NOT NULL DEFAULT 'shipping' COMMENT 'shipping / billing ',
    `house_no`  VARCHAR(256) ,
    `address1`  VARCHAR(256) NOT NULL DEFAULT 'Some Street',
    `address2`  VARCHAR(256),
    `town`  VARCHAR(256),
    `city`  VARCHAR(256),
    `county`  VARCHAR(256),
    `country`  VARCHAR(256),
    `postcode`  VARCHAR(32) NOT NULL DEFAULT 'AB12 3CD',
    `postcode_no_space`  VARCHAR(32) NOT NULL DEFAULT 'AB123CD',
    `lat` varchar(32) NOT NULL DEFAULT '51.507351',
    `lng` varchar(32) NOT NULL DEFAULT '-0.127758',
    `primary_address` tinyint(1) NOT NULL DEFAULT '0',
    `type_address` varchar(32) NOT NULL DEFAULT 'shipping' COMMENT 'shipping / billing ',
    PRIMARY KEY (`id`)
  ) ENGINE=InnoDB AUTO_INCREMENT=1 COLLATE='latin1_swedish_ci' COMMENT='###';